#Doped Horses Server Configuration
[DopedHorses]
	#Liste des blocs à rendre plus rapides. Format: <bloc>=<multiplier>.
	faster_blocks = ["dirt_path=0.7", ".*concrete=1.2"]
	#A horse speed is ~0.2, so if you put 0.2, the speed of the horse will be 0.4 so 2x faster.
	iron_shoe_speed_modifier = 0.05
	gold_shoe_speed_modifier = 0.08
	diamond_shoe_speed_modifier = 0.13
	netherite_shoe_speed_modifier = 0.18
	#round to .5 the value
	iron_shoe_armor_modifier = 5.0
	gold_shoe_armor_modifier = 2.5
	diamond_shoe_armor_modifier = 7.0
	netherite_shoe_armor_modifier = 10.0
	#Horse's jump strength ranges from 0.4–1.0, with an average of 0.7. A jump strength of 0.5 is enough to clear 1 9⁄16 blocks, while 1.0 is enough to clear 5 1⁄4 blocks.
	iron_shoe_jump_modifier = 0.2
	gold_shoe_jump_modifier = 0.4
	diamond_shoe_jump_modifier = 0.6
	netherite_shoe_jump_modifier = 0.8
	#A value between 0 and 1 (0.1 = 10%, 0.2=20% etc....), those items loots in chest in the nether / portal ruins
	iron_shoe_loot_chance = 0.15
	#A value between 0 and 1 (0.1 = 10%, 0.2=20% etc....), those items loots in chest in the nether / portal ruins
	gold_shoe_loot_chance = 0.1
	#A value between 0 and 1 (0.1 = 10%, 0.2=20% etc....), those items loots in chest in the nether / portal ruins
	diamond_shoe_loot_chance = 0.06
	#A value between 0 and 1 (0.1 = 10%, 0.2=20% etc....), those items loots in chest in the nether / portal ruins
	netherite_shoe_loot_chance = 0.03
